### ISSUE TITLE
Helium IoT Data Only Hotspot Forwarder

### ISSUE THREAD

**Issue by RideMyByte** [Wifx/lorix-os#2]
Hello everyone, 

I have now read several times that the Lorix One is also compatible with the **Helium** network. However, I can't find a way to connect the Lorix to Helium. It seems to require the [gateway-rs](https://github.com/helium/gateway-rs) on the other hand, the Lorix OS [changelog](https://iot.wifx.net/docs/lorix-os/1.1/lorix-one/release-notes/lorix-os-1-6-2) mention Helium as a forwarder from time to time. 

I am running 5 Lroxi One and would like to migrate to Helium. Preferably even use both LNS. Apparently Helium will only use ChirpStack instead of (open)LNS in the future? 
Very confusing... 

Have any of you got this up and running yet? 
Best regards and many thanks :)

**Comment by mullerch** [comment]
Hello RideMyByte,

Helium is not officially supported at this time on LORIX OS.

However, gateway-rs is available as a development opkg package in the LORIX OS feeds:

```
sudo opkg update
sudo opkg install helium-gateway
```

Here is a sample pmonitor file to run helium-gateway along other forwarders for dual network usage (only use one network for downlinks to respect duty-cycle):

```
    concentratord:
        description: LoRa concentrator daemon
        boot-order: 0
        process:
            run-mode: exec
            program-path: /opt/chirpstack-concentratord/chirpstack-concentratord
            program-arguments: -c /etc/opt/chirpstack-concentratord/00-concentratord.toml -c /etc/opt/chirpstack-concentratord/10-gateway.toml -c /etc/opt/chirpstack-concentratord/channels/channels.toml
            delays:
                start: 5000
                term: 5000
                restart: 5000
    gateway-bridge:
        description: Gateway Bridge receiveing the cocnentrator daemon packets and sending them to the ChirpStack Network Server
        boot-order: 1
        process:
            run-mode: exec
            program-path: /opt/chirpstack-gateway-bridge/chirpstack-gateway-bridge
            program-arguments: -c /etc/opt/chirpstack-gateway-bridge/10-general.toml -c /etc/opt/chirpstack-gateway-bridge/20-backend_concentratord.toml -c /etc/opt/chirpstack-gateway-bridge/30-integration.toml -c /etc/opt/chirpstack-gateway-bridge/40-filters.toml
            delays:
                start: 1000
                term: 1000
                restart: 5000
    helium-gateway:
        description: Helium Gateway packet forwarder
        boot-order: 2
        process:
            run-mode: exec
            program-path: /opt/helium-gateway/helium-gateway
            program-arguments: -c /etc/opt/helium-gateway/settings.toml server
            delays:
                start: 5000
                term: 10000
                restart: 5000
    udp-bridge:
        description: Bridges the concentratord to the Helium Gateway
        boot-order: 3
        process:
            run-mode: exec
            program-path: /opt/chirpstack-udp-bridge/chirpstack-udp-bridge
            program-arguments: -c /etc/opt/chirpstack-udp-bridge/00-concentratord.toml -c /etc/opt/chirpstack-udp-bridge/10-udp-bridge.toml -c /etc/opt/helium-gateway/chirpstack-udp-bridge/20-servers.toml
            delays:
                start: 5000
                term: 10000
                restart: 5000
```

You must also configure the several software in their config to connect together:

```
               ┌────udp-bridge────────gateway-rs
concentratord──┤
               └────gateway-bridge
```

Gateway registration by CLI in the Helium network was a bit painful, maybe they've improved.

Gateway often goes on deny list for rewards (even if data-only), as the sensitivity is "too good" and seems suspicious to their rules (typically when receiving beacon from a non LOS hotspot).

Here is an example of one of ours : https://heliumtracker.io/hotspots/226828
